apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: quay.io/bjoydeep/service-a:latest
        ports:
        - containerPort: 8080
        env:
        - name: DEPENDANT_SERVICE
          value: 'http://$(SERVICE_B_SERVICE_HOST):$(SERVICE_B_SERVICE_PORT)/callb'