apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 1
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: quay.io/bjoydeep/service-b:latest
        ports:
        - containerPort: 8090
        env:
        - name: DEPENDANT_SERVICE
          value: ""